language: php

php:
  - 5.5
  - 5.6

services:
  - redis-server
  - memcached

before_script:
  - composer install
  - phpenv config-add .travis.php.ini

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
